assert_lefthook_installed: true

post-merge:
  piped: true
  commands:
    "mise install":
      run: mise install -y

pre-push:
  parallel: true
  jobs:
    - name: "Run tests"
      run: cargo test --all --all-features

pre-commit:
  parallel: true
  jobs:
    - name: "Run clippy"
      run: cargo clippy --all --all-features

    - name: "Run fmt"
      run: cargo fmt --all
